instance BAN_1608_Kereth (Npc_Default)
{
//----------Info ogolne----------

name = "Kereth";
Npctype = npctype_main;
guild = GIL_BAU;
level = 14;
voice = 6;
id = 1608;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 276;
attribute[ATR_HITPOINTS] = 276;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Pony",101, 1,BAU_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_03);
EquipItem		(self, ItRw_Bow_Long_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_1608;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_1608 ()
{
	TA_sleep		(22,00,08,00,"BN_SEN_KERETH");
	TA_Sitaround		(08,00,22,00,"BN_SIAT_KERETH");
};
FUNC VOID Rtn_karczma_1608 ()
{
	TA_Stand		(22,00,08,00,"KERETH2");
	TA_Smoke		(08,00,22,00,"KERETH2");
};
//OW_PATH_067
FUNC VOID Rtn_follow_1608 ()
{
	TA_FollowPC		(22,00,08,00,"OW_PATH_067");
	TA_FollowPC		(08,00,22,00,"OW_PATH_067");
};