instance BAN_1615_Luis (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Luis";
Npctype = npctype_main;
guild = GIL_BAU;
level = 30;
voice = 7;
id = 1615;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 100;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Thief",104, 1,bau_armor_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,7);
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_03);
EquipItem		(self, ItRw_Bow_Long_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_1615;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_1615 ()
{
	TA_PickOre		(22,00,08,00,"ZL7");
	TA_PickOre		(08,00,22,00,"ZL7");
};
FUNC VOID Rtn_guide_1615 ()
{
	TA_GuidePC		(22,00,08,00,"SKRZYNIA_SZEFA_KOPALNI");
	TA_GuidePC		(08,00,22,00,"SKRZYNIA_SZEFA_KOPALNI");
};