instance NON_5603_Claw (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Claw";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 25;
voice = 11;
id = 5603;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 65;
attribute[ATR_DEXTERITY] = 55;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;
//----------Wyglad----------
Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",2,1,"Hum_Head_Thief",72,2,NON_WOLF_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);
//----------Umiejetnasci----------
Npc_SetTalentSkill (self, NPC_TALENT_BOW,2);
Npc_SetTalentSkill (self, NPC_TALENT_2H,7);
//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_New_06);
EquipItem		(self, ItRw_Bow_Long_05_Z);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItFoLoaf,3);
CreateInvItems  (self,ItFoMutton,3);
CreateInvItems  (self,Schutzring_Waffen1,1);
CreateInvItems  (self,ItMiNugget,55);
CreateInvItems  (self,ItMi_Alchemy_Salt_01,6);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5603;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5603 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_PotionAlchemy (06,00,09,33,"CLAW");
TA_PotionAlchemy (09,33,15,10,"CLAW");
TA_SitCampfire (15,10,06,00,"CLAW_CAMP");
};
FUNC VOID Rtn_chory_5603 ()
{//SPAWN_TALL_PATH_BANDITOS2_02
TA_Sleep (06,00,09,33,"BED_MYS");
TA_Sleep (09,33,15,10,"BED_MYS");
TA_Sleep (15,10,06,00,"BED_MYS");
};
func void Rtn_follow_5603 ()
{
TA_FOLLOWPC(06,00,18,00,"CLAW");
TA_FOLLOWPC(18,00,06,00,"CLAW");
};