instance NOV_1375_Hakan (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Hakan";
Npctype = Npctype_Main;
guild = GIL_NOV;
level = 10;
voice = 8;
id = 1375;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 30;
attribute[ATR_DEXTERITY] = 15;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 100;
attribute[ATR_HITPOINTS] = 100;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1 ,"Hum_Head_FatBald", 27 ,  1,NOV_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,4);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Hatchet_01);
CreateInvItems  (self,ItAt_Meatbug_01,5);
CreateInvItems  (self,ItFoApple,10);
CreateInvItems  (self,ItFoLoaf,15);
CreateInvItems  (self,ItFoMuttonRaw,9);
CreateInvItems  (self,ItFosoup,9);
CreateInvItems  (self,ItFoCrawlersoup,12);
CreateInvItems  (self,ItFo_Potion_Water_01,22);
CreateInvItems  (self,ItFo_Plants_Berrys_01,3);

CreateInvItems  (self,ItWe_PrzepisMoleratSoup,1);
CreateInvItems  (self,ItWe_PrzepisSnafSoup,1);
CreateInvItems  (self,ItWe_PrzepisCrawelSoup,1);
CreateInvItems  (self,ItWe_PrzepisScaSoup,1);
CreateInvItems  (self,przepis_zupaserowa,1);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine = Rtn_start_1375;

};

FUNC VOID Rtn_start_1375 ()
{
TA_Cook (06,00,12,00,"PSI_COOKER_01");
TA_Smoke (12,00,12,45,"PSI_COOKER_01");
TA_Cook (12,45,16,00,"PSI_COOKER_01");
TA_StandAround (16,00,16,20,"PSI_COOKER_01");
TA_Cook (16,20,20,00,"PSI_COOKER_01");
TA_SitCampfire (20,00,03,00,"PSI_COOKER_01");
TA_Stay (03,00,04,00,"PSI_COOKER_02");
TA_Smoke (04,00,06,00,"PSI_COOKER_02");
};
