instance Outlander (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name 		= "Outlander";
Npctype 	= Npctype_Main;
guild 		= GIL_BAU;
level 		= 10000;
voice 		= 13;
id 			= 155;
flags		= NPC_FLAG_IMMORTAL;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 200;
attribute[ATR_DEXTERITY] = 200;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 1000;
attribute[ATR_HITPOINTS] = 1000;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 2,"Hum_Head_Fighter",10, 2,GRD_ARMOR_I);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,10);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_04);
EquipItem		(self, ItRw_Crossbow_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_155;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_155 ()
{
TA_Guard (09,00,18,00,"WP_INTRO_WI16");
TA_Guard (18,00,09,00,"WP_INTRO_WI16"); //WP_INTRO_WI01
};


instance Radex (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name 		= "Radex";
Npctype 	= Npctype_Main;
guild 		= GIL_BAU;
level 		= 10000;
voice 		= 13;
id 			= 156;
flags		= NPC_FLAG_IMMORTAL;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 200;
attribute[ATR_DEXTERITY] = 200;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 1000;
attribute[ATR_HITPOINTS] = 1000;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 3,"Hum_Head_Fighter",10, 3,GRD_ARMOR_I);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

Npc_SetTalentSkill (self, NPC_TALENT_1H,10);
Npc_SetTalentSkill (self, NPC_TALENT_CROSSBOW,2);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_04);
EquipItem		(self, ItRw_Crossbow_01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_156;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_156 ()
{
TA_Guard (09,00,18,00,"WP_INTRO_WI01");
TA_Guard (18,00,09,00,"WP_INTRO_WI01"); //WP_INTRO_WI01
};

